"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestBaselineOfDebuggableASTInterpreter,
	#superclass : #PackageManifest,
	#category : #'BaselineOfDebuggableASTInterpreter-Manifest'
}

{ #category : #'code-critics' }
ManifestBaselineOfDebuggableASTInterpreter class >> ruleRBUtilityMethodsRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#BaselineOfDebuggableASTInterpreter)) #'2019-03-07T09:57:59.714146+01:00') )
]
